include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_relative_lib_imports
    - public_member_api_docs
    - prefer_relative_imports

analyzer:

formatter:
  page_width: 120
  trailing_commas: preserve
